# Generated by Django 6.1 on 2026-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', "O'qituvchi"), ('admin', 'Administrator'), ('boshliq', 'Boshliq')], default='teacher', max_length=10),
        ),
    ]
