# Generated by Django 6.1 on 2026-08-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('grade', models.PositiveSmallIntegerField(choices=[(7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf')])),
                ('chorak', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('hafta', models.PositiveSmallIntegerField()),
                ('cat', models.CharField(choices=[('mexanika', 'Mexanika'), ('termodinamika', 'Termodinamika'), ('elektr', 'Elektr'), ('optika', 'Optika'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20)),
                ('goal', models.TextField(blank=True)),
                ('goal_ru', models.TextField(blank=True)),
                ('goal_en', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('sim_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['grade', 'chorak', 'hafta'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('oddiy', 'Oddiy'), ('wow', 'Wow'), ('oyin', "O'yin")], default='oddiy', max_length=10)),
                ('desc', models.TextField(blank=True)),
                ('desc_ru', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('safety', models.TextField(blank=True)),
                ('safety_ru', models.TextField(blank=True)),
                ('safety_en', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='lessons.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
