# Generated by Django 6.1 on 2026-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_experiment_materials_en_experiment_materials_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chorak', models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (4, 4)], unique=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['chorak'],
            },
        ),
    ]
