# Generated by Django 6.1 on 2026-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlock',
            name='chorak',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], unique=True),
        ),
    ]
