# Generated by Django 6.1 on 2026-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_quarterlock_chorak'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf')])),
                ('hafta', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='lesson-posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grade', 'hafta', '-created_at'],
            },
        ),
    ]
