# Generated by Django 6.1 on 2026-09-15 07:56

from django.db import migrations, models

# Old physics-only grades (7/8/9) map onto the new grade-band scheme
# introduced by this migration. Defensive: production has zero Lesson
# rows as of this change, but this keeps any pre-existing data (e.g. a
# local dev fixture) consistent instead of silently leaving stale values.
# Runs AFTER the AlterField below: SQLite's TEXT-affinity column rebuild
# already turns the old integer 7/8/9 into the text digits '7'/'8'/'9' by
# itself, so this only needs to map those digit-strings to band codes.
OLD_GRADE_TO_BAND = {'7': '7-8', '8': '7-8', '9': '9'}


def forwards(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    for old_grade, band in OLD_GRADE_TO_BAND.items():
        if old_grade != band:
            Lesson.objects.filter(grade=old_grade).update(grade=band)


def backwards(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    band_to_old_grade = {'1-2': '1', '3-4': '3', '5-6': '5', '7-8': '7', '9': '9'}
    for band, old_grade in band_to_old_grade.items():
        if band != old_grade:
            Lesson.objects.filter(grade=band).update(grade=old_grade)


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessonposter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonPoster',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sim_id',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('1-2', '1-2-sinf'), ('3-4', '3-4-sinf'), ('5-6', '5-6-sinf'), ('7-8', '7-8-sinf'), ('9', '9-sinf')], max_length=3),
        ),
        migrations.RunPython(forwards, backwards),
    ]
