# Generated by Django 6.1 on 2026-09-16 17:22

from django.db import migrations, models


def merge_and_renumber(apps, schema_editor):
    """7-8 and 9 become one band ('7-8-9'). hafta is a continuous
    week-of-year counter *within a grade* (see lessons/views.py's
    _renumber_grade), so simply relabeling the grade would leave two
    lessons sharing the same (chorak, hafta) whenever both source
    grades had content in the same slot — renumber the merged set the
    same way a manual delete/reorder would."""
    Lesson = apps.get_model('lessons', 'Lesson')
    Lesson.objects.filter(grade__in=['7-8', '9']).update(grade='7-8-9')

    lessons = list(Lesson.objects.filter(grade='7-8-9').order_by('chorak', 'hafta', 'id'))
    for i, lesson in enumerate(lessons, start=1):
        lesson.hafta = i
    Lesson.objects.bulk_update(lessons, ['hafta'])


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_experiment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('1-2', '1-2-sinf'), ('3-4', '3-4-sinf'), ('5-6', '5-6-sinf'), ('7-8-9', '7-8-9-sinf')], max_length=5),
        ),
        # Irreversible: once merged, which lessons came from 7-8 vs 9 is lost.
        migrations.RunPython(merge_and_renumber, migrations.RunPython.noop),
    ]
