# Generated by Django 6.1 on 2026-08-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chorak', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(blank=True, max_length=500)),
                ('journal_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='journal.journalclass')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('journal_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('journal_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='journal.journalclass')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.classday')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.student')),
            ],
            options={
                'unique_together': {('student', 'day')},
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chorak', models.PositiveSmallIntegerField()),
                ('mark', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals', to='journal.student')),
            ],
            options={
                'unique_together': {('student', 'chorak')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('s', 'Sababli'), ('n', 'Sababsiz'), ('k', 'Kech')], max_length=1)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='journal.classday')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='journal.student')),
            ],
            options={
                'unique_together': {('student', 'day')},
            },
        ),
    ]
