# Generated by Django 6.1 on 2026-08-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('period_index', models.PositiveSmallIntegerField()),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('maktab', models.CharField(blank=True, max_length=255)),
                ('xona', models.CharField(blank=True, max_length=64)),
                ('sinf', models.CharField(blank=True, max_length=64)),
                ('span', models.PositiveSmallIntegerField(default=1)),
                ('band', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_index', 'period_index'],
                'unique_together': {('teacher', 'day_index', 'period_index')},
            },
        ),
    ]
