# Generated by Django 6.1 on 2026-09-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('nazariy', 'Nazariy'), ('amaliy', 'Amaliy')], max_length=16),
        ),
    ]
