# Generated by Django 6.1 on 2026-09-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableslot_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('nazariy', 'Nazariy'), ('amaliy', 'Amaliy'), ('engineering', 'Engineering')], max_length=16),
        ),
    ]
