# Generated by Django 6.1 on 2026-09-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetableslot_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='lesson_type',
        ),
    ]
