# Generated by Django 6.1 on 2026-09-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VapidKeys',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=128)),
                ('private_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'VAPID keys',
            },
        ),
    ]
